package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.model.TeamComposition;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;



// SPLIT PUSH

rule "Artillery, mid-late game, (split push)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "artillery",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an artillery in a split push comp your focus is to put pressure on enemies when they are trying to go for your solo laners. With your hard CC you can keep yourself safe whilist using your waveclear for maximum pressure.");
end

// Siege

rule "Artillery, mid-late game, (siege)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "artillery",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an artillery in a siege comp your one of the main parts of the team. You need to use your poke to get enemies to back away from the objectives, using waveclear to shove lanes with ease. You have hard CC in case enemies get close, so use it to keep a safe distance.");
end


// Protect

rule "Artillery, mid-late game, (protect)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "artillery",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an artillery in a protect comp your job is to get the enemies away from your team before they reach you. Since you are fairly ranged, you shouldn’t get close but in case they do get to you use your hard CC and devastate them. Waveclear should be fairly useful against enemies who shove lanes.");
end


// Attack

rule "Artillery, mid-late game, (attack)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "artillery",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an artillery in an attack comp you have one job and that is to be one of the main damage dealers in a fight. You are fairly squishy, but with your poke you can reach enemies even if you stay further away and with your hard CC you can turn tables in a fight easily.");
end


// Catch

rule "Artillery, mid-late game, (catch)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "artillery",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an artillery in a catch comp your job is to poke down enemies and when they are separate your team can take them down. Use your hard CC to prevent engages and teamfights, and your long range poke to overwhelm them so they lose the will to fight.");
end
