package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.model.TeamComposition;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;



// SPLIT PUSH


rule "Assassin, mid-late game, (split push), splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a split push comp you should focus on pushing towers, whilist eliminating unaware enemies who come to stop you. You have a lot of hard cc, so they shouldn’t be hard to deal with if you can lock them down. With your mobility moving around the map is crucial.");
end


rule "Assassin, mid-late game, (split push)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a split push comp you should focus on eliminating enemies that try to stop your solo laners. You have a lot of hard CC so it shouldn’t be a problem to kill unaware enemis and prevent them from escaping. With your mobility moving around the map shouldn’t be a problem.");
end


// Siege


rule "Assassin, mid-late game, (siege)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a siege comp your job is to prevent teamfights by killing their backline early. You have a lot of hard CC so they shouldn’t be able to escape you easily, but still be careful not to die in vain.");
end


// Protect


rule "Assassin, mid-late game, (protect)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a protect comp your position is to defend by attacking. You need to take out the enemy carries, so use your hard CC when you engage to prevent their escape and your disengage to get off scot free.");
end


// Attack


rule "Assassin, mid-late game, (attack)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in an attack comp your focus is to destroy the enemy backline. You have a hard engage, that will be devastating to the enemy and using your hard CC you can lock them down and prevent their escape. ");
end



// Catch


rule "Assassin, mid-late game, (catch)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a catch comp your focus is to take out enemies before fights to give yourself an edge. You have a lot of CC and combining that with your hard engages, not many enemies should be able to avoid it. If things get out of hand use your mobility to reposition and try again.");
end
