package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;

//Diver
//
//    aggro
//
//        vs Juggernaut

rule "Diver vs Juggernaut, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that juggernauts can sustain a lot of damage, and even dish some back which makes it difficult to kill them in a 1v1 situation.");
end

//        vs Diver

rule "Diver vs Diver, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, you will have an advantage by using your CC to secure trades in your favor, but know how and when to engage to secure a kill. They are highly mobile and can put pressure on you quite quickly, but they shouldn’t present a problem if you control the situation first.");
end

//        vs Assassin

rule "Diver vs Assassin, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, you will have an advantage by using your CC to secure trades in your favor, but know how and when to engage to secure a kill. They are rather mobile and can burst you down when you least expect it, but they shouldn’t present a problem if you control the situation first.");
end


//        vs Skirmisher

rule "Diver vs Skirmisher, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, they will match your hard engages but struggle against mobility. Using your CC you can secure trades in your favor, but know that even though skirmishers are not as mobile, but they have the toolkit to deal with every situation.");
end

//        vs Marksman

rule "Diver vs Marksman, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time.");
end


//        vs Burst

rule "Diver vs Burst, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a burster, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know bursters have a lot of CC, and once you are locked down they will burst you with ease.");
end

//        vs Battlemage

rule "Diver vs Battlemage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know with their highly sustainable damage you need to be careful in prolonged fights.");
end

//        vs Artillery

rule "Diver vs Artillery, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that using their poke and long range you will get punished all the time, so try to get in close.");
end

//        vs Vanguard

rule "Diver vs Vanguard, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that with a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end

//        vs Warden

rule "Diver vs Warden, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
				playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that they are impenetrable tanks, with a lot of sustain and it will be very hard to defeat them.");
end


//        vs Catcher

rule "Diver vs Catcher, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that they specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them.");
end

//        vs Enchanter

rule "Diver vs Enchanter, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, because they are quite fragile on their own, but with their wast utility they can keep themselves and others safe.");
end

//    end aggro


    
//    def
//
//        vs Juggernaut

rule "Diver vs Juggernaut, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, you need to understand that what they lack in mobility they make up in damage and sustain. They can lock you down and deal a lot of damage, so use your CC to keep them at bay and if needed disengage to escape, so do not be afraid to trade.");
end

//        vs Diver

rule "Diver vs Diver, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, with their hard engage and mobility you really need to be careful how you position. They can engage quickly for a lot of damage, so use your CC to keep them at bay and if needed disengage to escape, so do not be afraid to trade.");
end


//        vs Assassin

rule "Diver vs Assassin, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so use your CC to keep them at bay and if needed disengage to escape, so do not be afraid to trade.");
end

//        vs Skirmisher

rule "Diver vs Skirmisher, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skrimisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure, so use your CC to keep them at bay and if needed disengage to escape.");
end

//        vs Marksman

rule "Diver vs Marksman, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with their ranged damage and poke you need to be able to witstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan, so use your CC to punish their misspositioning and if needed disengage to escape.");
end


//        vs Burst

rule "Diver vs Burst, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against bursters, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

//        vs Battlemage

rule "Diver vs Battlemage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time, so use your CC to punish their misspositioning and if needed disengage to escape.");
end


//        vs Artillery

rule "Diver vs Artillery, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be carefull against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

//        vs Vanguard

rule "Diver vs Vanguard, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so quick trades should be in your favor, so use your CC when you trade and if needed disengage to escape.");
end

//        vs Warden

rule "Diver vs Warden, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain, so use your CC when you trade and if needed disengage to escape.");
end

//        vs Catcher

rule "Diver vs Catcher, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than, so use your CC to punish their misspositioning and if needed disengage to escape.");
end


//        vs Enchanter

rule "Diver vs Enchanter, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelesll. Use your CC to punish their misspositioning and if needed disengage to escape.");
end


//    end def

