package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;

//Diver
//
//    aggro
//
//        vs Juggernaut

rule "Diver vs Juggernaut, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that juggernauts can sustain a lot of damage, and even dish some back which makes it difficult to kill them in a 1v1 situation.");
end

rule "Diver vs Juggernaut, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, use your CC wisely to secure trades in your favor getting in and out of trades quickly, but know that juggernauts can sustain a lot of damage, and even dish some back which makes it difficult to kill them in a 1v1 situation.");
end

rule "Diver vs Juggernaut, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, it will be difficult for you to trade fairly even if you have an advantage but that doesn’t mean it is impossible. You are more mobile so use it to get in and get out of trades, but know that juggernauts can sustain a lot of damage, and even dish some back which makes it difficult to kill them in a 1v1 situation.");
end

//        vs Diver

rule "Diver vs Diver, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, you will have an advantage by using your CC to secure trades in your favor, but know how and when to engage to secure a kill. They are highly mobile and can put pressure on you quite quickly, but they shouldn’t present a problem if you control the situation first.");
end

rule "Diver vs Diver, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, you will have an advantage by using your CC to secure trades in your favor, but be wary as they are highly mobile and can put pressure on you quite quickly, but they shouldn’t present a problem if you control the situation first.");
end

rule "Diver vs Diver, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, you will be in trouble if you were to fight against them when they engage on you, so try to trade when you know they miss position. They are highly mobile and can put pressure on you quite quickly, but they shouldn’t present a problem if you control the situation first.");
end

//        vs Assassin

rule "Diver vs Assassin, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, you will have an advantage by using your CC to secure trades in your favor, but know how and when to engage to secure a kill. They are rather mobile and can burst you down when you least expect it, but they shouldn’t present a problem if you control the situation first.");
end

rule "Diver vs Assassin, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, you will have an advantage by using your CC to secure trades in your favor, but be wary as they are rather mobile and can burst you down when you least expect it, but they shouldn’t present a problem if you control the situation first.");
end

rule "Diver vs Assassin, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, you will be in trouble if you were to fight against them when they engage on you, so try to trade when you know they missposition. They are rather mobile and can burst you down when you least expect it, but they shouldn’t present a problem if you control the situation first.");
end

//        vs Skirmisher

rule "Diver vs Skirmisher, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, they will match your hard engages but struggle against mobility. Using your CC you can secure trades in your favor, but know that even though skirmishers are not as mobile, but they have the toolkit to deal with every situation.");
end

rule "Diver vs Skirmisher, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, use your CC wisely to secure trades in your favor getting in and out of trades quickly, but know that even though skirmishers are not as mobile, but they have the toolkit to deal with every situation.");
end

rule "Diver vs Skirmisher, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, it will be difficult for you to trade fairly even if you have an advantage but that doesn’t mean it is impossible. You are more mobile so use it to get in and get out of trades, but know that even though skirmishers are not as mobile, but they have the toolkit to deal with every situation.");
end

//        vs Marksman

rule "Diver vs Marksman, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time.");
end

rule "Diver vs Marksman, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, use your CC wisely when they overstep to get trades to go in your favor, but know that marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time.");
end

rule "Diver vs Marksman, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, it will be difficult for you to trade since they have the advantage. You are more mobile so use it to get in and get out of trades, but know that marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time.");
end

//        vs Burst

rule "Diver vs Burst, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a burster, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know bursters have a lot of CC, and once you are locked down they will burst you with ease.");
end

rule "Diver vs Burst, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a burster, use your CC wisely when they overstep to get trades to go in your favor, but know bursters have a lot of CC, and once you are locked down they will burst you with ease.");
end

rule "Diver vs Burst, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a burster, it will be difficult for you to trade since they have the advantage. You are more mobile so use it to get in and get out of trades, but know bursters have a lot of CC, and once you are locked down they will burst you with ease.");
end

//        vs Battlemage

rule "Diver vs Battlemage, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know with their highly sustainable damage you need to be careful in prolonged fights.");
end

rule "Diver vs Battlemage, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, use your CC wisely when they overstep to get trades to go in your favor, but know with their highly sustainable damage you need to be careful in prolonged fights.");
end

rule "Diver vs Battlemage, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, it will be difficult for you to trade since they have the advantage. You are more mobile so use it to get in and get out of trades, but know with their highly sustainable damage you need to be careful in prolonged fights.");
end

//        vs Artillery

rule "Diver vs Artillery, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that using their poke and long range you will get punished all the time, so try to get in close.");
end

rule "Diver vs Artillery, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, use your CC wisely when they overstep to get trades to go in your favor, but know that using their poke and long range you will get punished all the time, so try to get in close.");
end

rule "Diver vs Artillery, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, it will be difficult for you to trade since they have the range advantage. You are more mobile so use it to get in and get out of trades, but know that using their poke and long range you will get punished all the time, so try to get in close.");
end

//        vs Vanguard

rule "Diver vs Vanguard, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that with a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end

rule "Diver vs Vanguard, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, use your CC wisely to secure trades in your favor getting in and out of trades quickly, but know that with a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end

rule "Diver vs Vanguard, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, it will be difficult for you to trade fairly even if you have an advantage but that doesn’t mean it is impossible. You are more mobile so use it to get in and get out of trades, but know that with a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end

//        vs Warden

rule "Diver vs Warden, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that they are impenetrable tanks, with a lot of sustain and it will be very hard to defeat them.");
end

rule "Diver vs Warden, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, use your CC wisely to secure trades in your favor getting in and out of trades quickly, but know that they are impenetrable tanks, with a lot of sustain and it will be very hard to defeat them.");
end

rule "Diver vs Warden, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, it will be difficult for you to trade fairly even if you have an advantage. You are more mobile so use it to get in and get out of trades, but know that they are impenetrable tanks, with a lot of sustain and it will be very hard to defeat them.");
end

//        vs Catcher

rule "Diver vs Catcher, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, but know that they specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them.");
end

rule "Diver vs Catcher, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, use your CC wisely when they overstep to get trades to go in your favor, but know that they specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them.");
end

rule "Diver vs Catcher, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, it will be difficult for you to trade since they have the range advantage. You are more mobile so use it to get in and get out of trades, but know that they specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them.");
end

//        vs Enchanter

rule "Diver vs Enchanter, ally hardCC and hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, they will struggle against your hard engages and mobility. Using your CC you can secure trades in your favor, because they are quite fragile on their own, but with their wast utility they can keep themselves and others safe.");
end

rule "Diver vs Enchanter, ally hardCC and no hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, use your CC wisely when they overstep to get trades to go in your favor, because they are quite fragile on their own, but with their wast utility they can keep themselves and others safe.");
end

rule "Diver vs Enchanter, ally nothing, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, it will be difficult for you to trade since they have the range advantage. You are more mobile so use it to get in and get out of trades. They are quite fragile on their own, but with their wast utility they can keep themselves and others safe.");
end

//    end aggro


    
//    def
//
//        vs Juggernaut

rule "Diver vs Juggernaut, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, you need to understand that what they lack in mobility they make up in damage and sustain. They can lock you down and deal a lot of damage, so use your CC to keep them at bay and if needed disengage to escape, so do not be afraid to trade.");
end

rule "Diver vs Juggernaut, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, you need to understand that what they lack in mobility they make up in damage and sustain. They can lock you down and deal a lot of damage, so use your CC to keep them at bay and be careful when you trade.");
end

rule "Diver vs Juggernaut, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, you need to understand that what they lack in mobility they make up in damage and sustain. They can lock you down and deal a lot of damage, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Diver

rule "Diver vs Diver, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, with their hard engage and mobility you really need to be careful how you position. They can engage quickly for a lot of damage, so use your CC to keep them at bay and if needed disengage to escape, so do not be afraid to trade.");
end

rule "Diver vs Diver, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another diver, with their hard engage and mobility you really need to be careful how you position. They can engage quickly for a lot of damage, so use your CC to keep them at bay and be careful when you trade.");
end

rule "Diver vs Diver, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a diver, with their hard engage and mobility you really need to be careful how you position. They can engage quickly for a lot of damage, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Assassin

rule "Diver vs Assassin, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so use your CC to keep them at bay and if needed disengage to escape, so do not be afraid to trade.");
end

rule "Diver vs Assassin, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so use your CC to keep them at bay and be careful when you trade.");
end

rule "Diver vs Assassin, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Skirmisher

rule "Diver vs Skirmisher, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skrimisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure, so use your CC to keep them at bay and if needed disengage to escape.");
end

rule "Diver vs Skirmisher, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skrimisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure, so use your CC to keep them at bay and be careful when you trade.");
end

rule "Diver vs Skirmisher, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skrimisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Marksman

rule "Diver vs Marksman, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with their ranged damage and poke you need to be able to witstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

rule "Diver vs Marksman, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with their ranged damage and poke you need to be able to witstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan, so use your CC to punish their misspositioning and stop their engages.");
end

rule "Diver vs Marksman, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with their ranged damage and poke you need to be able to witstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Burst

rule "Diver vs Burst, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against bursters, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

rule "Diver vs Burst, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against bursters, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable, so use your CC to punish their misspositioning and stop their engages.");
end

rule "Diver vs Burst, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against bursters, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Battlemage

rule "Diver vs Battlemage, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

rule "Diver vs Battlemage, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time, so use your CC to punish their misspositioning and stop their engages.");
end

rule "Diver vs Battlemage, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time, so play more passively while awaiting assistance from your jungler for a kill.");
end

//        vs Artillery

rule "Diver vs Artillery, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be carefull against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

rule "Diver vs Artillery, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be carefull against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range, so use your CC to punish their misspositioning and stop their engages.");
end

rule "Diver vs Artillery, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be carefull against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range, so use your CC to punish their misspositioning and stop their engages.");
end

//        vs Vanguard

rule "Diver vs Vanguard, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so quick trades should be in your favor, so use your CC when you trade and if needed disengage to escape.");
end

rule "Diver vs Vanguard, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so quick trades should be in your favor, so use your CC when you trade.");
end

rule "Diver vs Vanguard, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so quick trades should be in your favor, so try to trade a bit while awaiting assistance from your jungler for a kill.");
end

//        vs Warden

rule "Diver vs Warden, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain, so use your CC when you trade and if needed disengage to escape.");
end

rule "Diver vs Warden, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain, so use your CC when you trade.");
end

rule "Diver vs Warden, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain, so try to trade a bit while awaiting assistance from your jungler for a kill.");
end

//        vs Catcher

rule "Diver vs Catcher, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than, so use your CC to punish their misspositioning and if needed disengage to escape.");
end

rule "Diver vs Catcher, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than, so use your CC to punish their misspositioning and stop their engages.");
end

rule "Diver vs Catcher, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than, so play more aggressively when their abilitites are off cooldown while awaiting assistance from your jungler for a kill.");
end

//        vs Enchanter

rule "Diver vs Enchanter, ally hardCC and disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelesll. Use your CC to punish their misspositioning and if needed disengage to escape.");
end

rule "Diver vs Enchanter, ally hardCC and no disengage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelessly . Use your CC to punish their misspositioning and stop their engages.");
end

rule "Diver vs Enchanter, ally nothing, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "diver",
			$allyLane: lane,
			hardCC == false,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelessly. They are not as strong at close range, but you should still play more passively while awaiting assistance from your jungler for a kill.");
end

//    end def

