package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;

rule "Ally strong early, enemy isn't"
	when
		$ally : AllyChampion(
			!lane.equals("jungle"),
			goodEarly == true,
			$allyLane: lane
		)
		$enemy : EnemyChampion(
			lane.equals($allyLane),
			goodEarly == false
		)
	then
		modify($ally){setPlayType("aggro");}
end

