package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.model.TeamComposition;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;

// Juggernaut, mid game, (comp: SPLIT_PUSH) 

rule "Juggernaut, mid game, (split push), ally sustain, hardCC and splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a split push team comp you should focus on trying to push the lane as much as you can, whilst attracting attention from the enemy laners. With your hard CC, they shouldn’t be a problem to deal with and if you need a means to escape it can be useful there as well. You do have a lot of sustain, so do not worry about having to back off from a lane. As soon as they leave try pushing again.");
end

rule "Juggernaut, mid game, (split push), ally sustain and splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == false,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a split push team comp you should focus on trying to push the lane as much as you can, whilst attracting attention from the enemy laners. You do have a lot of sustain, so do not worry about losing trades, as you can continue to put pressure on them without going back to base.");
end

rule "Juggernaut, mid game, (split push), ally sustain and hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true,
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a split push team comp you should be a good meatshield for your team, while others push lanes. You do have a lot of sustain, so do not worry about fighting and using your hard CC you can prolong fights as well.");
end


// Juggernaut, late game, (comp: SPLIT_PUSH) 

rule "Juggernaut, late game, (split push), ally sustain, hardCC and splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "You should still focus on trying to push the lane as much as you can, whilst attracting attention from the enemy laners. With your hard CC, they shouldn’t be a problem to deal with and if you need a means to escape it can be useful there as well. You do have a lot of sustain, so do not worry about having to back off from a lane. Try to reposition to take objectives, but do not wander far from your position.");
end

rule "Juggernaut, late game, (split push), ally sustain and splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == false,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "You should still focus on trying to push the lane as much as you can, whilst attracting attention from the enemy laners. You do have a lot of sustain, so do not worry about losing fights, as you can continue to put pressure on them without going back to base. Try to reposition to take objectives, but do not wander far from your position.");
end

rule "Juggernaut, late game, (split push), ally sustain and hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true,
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "You should still be a good meatshield for your team, while others push lanes. You do have a lot of sustain, so do not worry about fighting and using your hard CC you can prolong fights as well. Objective control is key here.");
end







// Juggernaut, mid game, (comp: SIEGE) 


rule "Juggernaut, mid game, (siege), ally sustain and hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a siege comp your position is to defend your teammates in fights and protect objectives. You have a lot of sustain, so you can take a beating and with your hard CC fights can be turned to your favor.");
end


// Juggernaut, late game, (comp: SIEGE) 


rule "Juggernaut, late game, (siege), ally sustain and hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "You should still position yourself between your team and the enemy team, using your hard CC to avoid fighting and sustain to outlive undesirable outcomes.");
end





// Juggernaut, mid game, (comp: PROTECT) 

rule "Juggernaut, mid game, (protect), ally sustain and hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a protect comp your position is to defend your teammates in fights and protect objectives. You have a lot of sustain, so you can take a beating and with your hard CC fights can be turned to your favor.");
end



// Juggernaut, late game, (comp: PROTECT) 

rule "Juggernaut, late game, (protect), ally sustain and hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			sustain == true,
			hardCC == true
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "You should still position yourself between your team and the enemy team, using your hard CC to avoid fighting and sustain to outlive undesirable outcomes.");
end






// Juggernaut, mid game, (comp: ATTACK) 

rule "Juggernaut, mid game, (attack), ally hardCC, hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in an attack comp your focus is to deal as much damage as possible to the enemy team, devastating them in fights. Using your hard engage you can start fights and with hard CC you will be able to punish their misplays easily.");
end

rule "Juggernaut, mid game, (attack), ally hardCC and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in an attack comp your focus is to deal as much damage as possible to the enemy team, devastating them in fights. Using your hard CC you will be able to punish their misplays easily.");
end

rule "Juggernaut, mid game, (attack), ally hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == false,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in an attack comp your focus is to deal as much damage as possible to the enemy team, devastating them in fights. Using your hard engage you can create fight opportunities for your team to take the lead.");
end







// Juggernaut, late game, (comp: ATTACK) 

rule "Juggernaut, late game, (attack), ally hardCC, hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "Your focus should still be to deal as much damage as possible to the enemy team, devastating them in fights. Using your hard engage you can start fights and with hard CC you will be able to punish their misplays easily.");
end

rule "Juggernaut, late game, (attack), ally hardCC and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "Your focus should still be to deal as much damage as possible to the enemy team, devastating them in fights. Using your hard CC you will be able to punish their misplays easily.");
end

rule "Juggernaut, late game, (attack), ally hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == false,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "Your focus should still be to deal as much damage as possible to the enemy team, devastating them in fights. Using your hard engage you can create fight opportunities for your team to take the lead.");
end






// Juggernaut, mid game, (comp: CATCH) 

rule "Juggernaut, mid game, (catch), ally hardCC, hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a catch comp your focus should be to distract the enemy team whilst your teammates take them out unexpectedly. With your hard CC you can prolong fights, and using your hard engage you can start fights when the enemy is lacking in numbers.");
end


rule "Juggernaut, mid game, (catch), ally hardCC and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a catch comp your focus should be to distract the enemy team whilst your teammates take them out unexpectedly. With your hard CC you can prolong fights, and using your sustain you will be able to survive for longer.");
end


rule "Juggernaut, mid game, (catch), ally hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == false,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "As a juggernaut in a catch comp your focus should be to distract the enemy team whilst your teammates take them out unexpectedly. With your hard engage you can start fights when the enemy is lacking in numbers and outsustain anything they throw at you.");
end






// Juggernaut, late game, (comp: CATCH) 

rule "Juggernaut, late game, (catch), ally hardCC, hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "Your focus should still be to distract the enemy team whilst your teammates take them out unexpectedly. With your hard CC you can prolong fights, and using your hard engage you can start fights when the enemy is lacking in numbers. Try to rotate for objectives when you know the enemy cant force fights.");
end


rule "Juggernaut, late game, (catch), ally hardCC and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "As a juggernaut in a catch comp your focus should be to distract the enemy team whilst your teammates take them out unexpectedly. With your hard CC you can prolong fights, and using your sustain you will be able to survive for longer. Try to rotate for objectives when you know the enemy cant force fights.");
end


rule "Juggernaut, late game, (catch), ally hardEngage and sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "juggernaut",
			$allyLane : lane,
			hardCC == false,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "late", "As a juggernaut in a catch comp your focus should be to distract the enemy team whilst your teammates take them out unexpectedly. With your hard engage you can start fights when the enemy is lacking in numbers and outsustain anything they throw at you. Try to rotate for objectives when you know the enemy cant force fights.");
end




