package com.sample.rules

import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.AdviceStorage;

global com.sample.AdviceStorage adviceStorage;

//Marksman vs Juggernaut (aggro)

rule "Marksman vs Juggernaut, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Juggernauts can sustain a lot of damage, and even dish some back which makes it difficult to kill them alone.");
end

//Marksman vs Diver (aggro)




rule "Marksman vs Diver, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a diver, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Be careful as divers are highly mobile and can put pressure on you quite quickly, so try to stay out of their range.");
end

//Marksman vs Assassin (aggro)


rule "Marksman vs Assassin, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a diver you shouldn’t have problems as long as you stay out of their engage reach. You can secure trades with your long range poke and control the lane to punish him with waveclear. Be wary as they are rather mobile and can burst you down when you least expect it.");
end


//Marksman vs Skirmisher (aggro)



rule "Marksman vs Skirmisher, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Skirmishers are not as mobile, but they have the toolkit to deal with every situation, so be careful when you engage in fights.");
end



//Marksman vs Marksman (aggro)


rule "Marksman vs Marksman, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another marksman, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time, so try to punish their misspositoning.");
end



//Marksman vs Burst (aggro)


rule "Marksman vs Burst, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a burster, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Bursters have a lot of CC, and once you are locked down they will burst you with ease, so try to bait out their engages.");
end


//Marksman vs Battlemage (aggro)

rule "Marksman vs Battlemage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Battlemages have their highly sustainable damage so you need to be careful in prolonged fights");
end

//Marksman vs Artillery (aggro)


rule "Marksman vs Artillery, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, you will be at a range disadvantage. You can secure trades with your long range poke and control the lane to punish him with waveclear. Using their poke and long range you will get punished all the time, so try to get in close.");
end

//Marksman vs Vanguard (aggro)

rule "Marksman vs Vanguard, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. With a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end


//Marksman vs Warden (aggro)


rule "Marksman vs Warden, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. Impenetrable tanks, with a lot of sustain it will be best to first poke them down.");
end

//Marksman vs Catcher (aggro)

rule "Marksman vs Catcher, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, you shouldn’t have problems as long as you stay at a safe distance. You can secure trades with your long range poke and control the lane to punish him with waveclear. They specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them, so be careful how you position.");
end




//Marksman vs Enchanter (aggro)


rule "Marksman vs Enchanter, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you will be at a range advantage. You can secure trades with your long range poke and control the lane to punish him with waveclear. They are quite fragile on their own, but with their wast utility they can keep themselves and others safe.");
end

//Marksman vs Juggernaut (def)

rule "Marksman vs Juggernaut, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, you need to understand that what they lack in mobility they make up in damage and sustain. They can lock you down and deal a lot of damage, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you have an range advantage but know it will be hard to go for a kill.");
end


//Marksman vs Diver (def)

rule "Marksman vs Diver, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a diver, with their hard engage and mobility you really need to be careful how you position. They can engage quickly for a lot of damage, so use your CC to keep them at bay and disengage from close fights. Be careful how you trade, even if you have an range advantage because they can close the distance easily.");
end


//Marksman vs Assassin (def)

rule "Marksman vs Assassin, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so use your CC to keep them at bay and disengage from close fights. Be careful how you trade, even if you have an range advantage because they can close the distance easily.");
end

//Marksman vs Skirmisher (def)

rule "Marksman vs Skirmisher, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you have an range advantage but know it will be hard to go for a kill.");
end

//Marksman vs Marksman (def)

rule "Marksman vs Marksman, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against another marksman, with their ranged damage and poke you need to be able to withstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you also have a fair bit of range, but be careful of misspositioning.");
end



//Marksman vs Burst (def)

rule "Marksman vs Burst, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a burster, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you also have a fair bit of range, but be careful of misspositioning.");
end

//Marksman vs Battlemage (def)

rule "Marksman vs Battlemage, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you also have a fair bit of range, but be careful of prolonged fights.");
end


//Marksman vs Artillery (def)

rule "Marksman vs Artillery, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be careful against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you also have a fair bit of range, but be careful of their poke.");
end


//Marksman vs Vanguard (def)

rule "Marksman vs Vanguard, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so quick trades should be in your favor, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you have an range advantage but know it will be hard to go for a kill.");
end

//Marksman vs Warden (def)

rule "Marksman vs Warden, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you have an range advantage but know it will be hard to go for a kill.");
end

//Marksman vs Catcher (def)

rule "Marksman vs Catcher, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than, so use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you also have a fair bit of range, but be careful of misspositioning.");
end


//Marksman vs Enchanter (def)

rule "Marksman vs Enchanter, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane: lane,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelessly . Use your CC to keep them at bay and disengage from close fights. Do not be afraid to trade, since you also have a fair bit of range.");
end
