package com.sample.rules
 
import com.sample.DroolsTest.Message;
import com.sample.model.Champion;
import com.sample.model.AllyChampion;
import com.sample.model.EnemyChampion;
import com.sample.AdviceStorage;
 

 
//---------------------- Off
		
		
rule "Warden vs Juggernaut, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, with your engage and hard crowd control you can lock them down and set up small trades in your favor. Be careful as they have high sustain, so some trades wont go in your favor at all and prolonging trades will definitely result in your lose.");
end


rule "Warden vs Juggernaut, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, hard crowd control can lock them down and allow you to set up small trades in your favor. Be careful as they have high sustain, so some trades wont go in your favor at all and prolonging trades will definitely result in your lose.");
end



rule "Warden vs Diver, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a diver, with your engage and hard crowd control you can lock them down and set up small trades in your favor. Be wary that divers are highly mobile and can put pressure on you quite quickly, but with your sustain they shouldn’t be a problem in shorter trades.");
end


rule "Warden vs Diver, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a diver, hard crowd control can lock them down and allow you to set up small trades in your favor. Be wary that divers are highly mobile and can put pressure on you quite quickly, but with your sustain they shouldn’t be a problem in shorter trades.");
end




rule "Warden vs Assassin, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with your engage and hard crowd control you can lock them down and set up small trades in your favor. Assassins are rather mobile and can attempt to burst you down when you least expect it, but with your sustain they shouldn’t be able to. ");
end


rule "Warden vs Assassin, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an assassin, hard crowd control can lock them down and allow you to set up small trades in your favor. Assassins are rather mobile and can attempt to burst you down when you least expect it, but with your sustain they shouldn’t be able to. ");
end




rule "Warden vs Skirmisher, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, be careful how you engage as they can handle that fairly well, so try to use your CC to keep up the advantage in a fight. Be careful as even though skirmishers are not as mobile, but they have the toolkit to deal with every situation, so try to keep your trades short.");
end


rule "Warden vs Skirmisher, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a skirmisher, hard crowd control can lock them down and allow you to set up small trades in your favor. Be careful as even though skirmishers are not as mobile, but they have the toolkit to deal with every situation, so try to keep your trades short.");
end

	
	
	

rule "Warden vs Marksman, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a marksman, using your engage will give you an advantage to follow up and use your CC to set up kills or ganks for your jungler. Be careful as marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time, and with your lack of damage it will be hard to deal with them.");
end


rule "Warden vs Marksman, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with your crowd control you can lock them down when they get to close, but it will be troublesome to approach them since marksman are mobile long range damage dealers, that can punish you over a sustainable amount of time, and with your lack of damage it will be hard to deal with them.");
end
	
	
	
	
rule "Warden vs Burst, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a burster, using your engage will give you an advantage to follow up and use your CC to set up kills or ganks for your jungler. Be careful as bursters have a lot of CC and burst potential, but with your lack of damage it will be hard to deal with them.");
end


rule "Warden vs Burst, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a burster, with your crowd control you can lock them down when they get to close, but it will be troublesome to approach them since bursters have a lot of CC and burst potential, but with your lack of damage it will be hard to deal with them.");
end
	
	
	
	
rule "Warden vs Battlemage, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, using your engage will give you an advantage to follow up and use your CC to set up kills or ganks for your jungler. Be careful as battlemages have their highly sustainable damage so you need to be careful in prolonged fights.");
end


rule "Warden vs Battlemage, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with your crowd control you can lock them down when they get to close, but it will be troublesome to approach them since battlemages have their highly sustainable damage so you need to be careful in prolonged fights.");
end
	
	
	
		
rule "Warden vs Artillery, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an artillery, using your engage will give you an advantage to follow up and use your CC to set up kills or ganks for your jungler. Be careful as with their poke and long range you will get punished all the time, so try to get in close.");
end


rule "Warden vs Artillery, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with your crowd control you can lock them down when they get to close, but it will be troublesome to approach them since with their poke and long range you will get punished all the time.");
end
	
	
	
			
rule "Warden vs Vanguard, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, with your engage and hard crowd control you can lock them down and set up small trades in your favor. Be careful as with a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end


rule "Warden vs Vanguard, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, hard crowd control can lock them down and allow you to set up small trades in your favor. Be careful as with a lot of sustain, they are quite hard to take down but with overall good damage can be hassle to fight against.");
end


			
rule "Warden vs Warden, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against another warden, with your engage and hard crowd control you can lock them down and set up small trades in your favor. Be careful as they are impenetrable tanks, with a lot of sustain and it will feel like it’s almost impossible to defeat them.");
end


rule "Warden vs Warden, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against another warden, hard crowd control can lock them down and allow you to set up small trades in your favor. Be careful as they are impenetrable tanks, with a lot of sustain and it will feel like it’s almost impossible to defeat them.");
end
		
		
		
		
rule "Warden vs Catcher, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a burster, using your engage will give you an advantage to follow up and use your CC to set up kills or ganks for your jungler. Be careful as catchers specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them.");
end


rule "Warden vs Catcher, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a catcher, with your crowd control you can lock them down when they get to close, but it will be hard to fight them since catchers specialize in area lockdowns, using their overwhelming CC to lock down opponents and punish them.");
end
		
		
		

rule "Warden vs Enchanter, ally hardCC + hardEngage, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == true,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, using your engage will give you an advantage to follow up and use your CC to set up kills or ganks for your jungler. They are quite fragile on their own, but with their wast utility they can keep themselves and others safe.");
end


rule "Warden vs Enchanter, ally hardCC, ally aggro"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			hardEngage == false,
			playType == "aggro"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a enchanter, with your crowd control you can lock them down when they get to close, but it will be troublesome to kill them because even though they are quite fragile on their own, with their wast utility they can keep themselves and others safe.");
end


//------------------- Def



rule "Warden vs Juggernaut, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, with their hard CC and often hurtful trades you really need to be careful when you pick your fights. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but be careful to not waste it.");
end


rule "Warden vs Juggernaut, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "juggernaut"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a juggernaut, with their hard CC and often hurtful trades you really need to be careful when you pick your fights. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end
	



rule "Warden vs Diver, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a diver, with their hard engage and mobility you need to be careful how you position. They can engage quickly for a lot of damage, so you should be safe in trades with your sustain and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but be careful to not waste it as they can chase with their mobility.");
end


rule "Warden vs Diver, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "diver"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a diver, with their hard engage and mobility you need to be careful how you position. They can engage quickly for a lot of damage, so you should be safe in trades with your sustain and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler");
end
	



rule "Warden vs Assassin, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so you should be safe in trades with your sustain and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but be careful to not waste it as they can chase with their mobility.");
end


rule "Warden vs Assassin, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "assassin"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an assassin, with their burst potential and mobility you really need to be careful how you position. They are very mobile and hard to deal with, so you should be safe in trades with your sustain and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler");
end
	



rule "Warden vs Skirmisher, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but be careful to not waste it.");
end



rule "Warden vs Skirmisher, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "skirmisher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a skrimisher, with their durability in fights and high damage output you need to choose your duels carefully. They lack in gap closers, but they make it up in lane pressure. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end





rule "Warden vs Marksman, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with their ranged damage and poke you need to be able to withstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but avoid getting in their attack range either way.");
end
	




rule "Warden vs Marksman, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "marksman"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a marksman, with their ranged damage and poke you need to be able to withstand it during the laning phase. They are not as tanky, so trading and killing them once they are low should be the plan. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end
	



rule "Warden vs Burst, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a burster, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but avoid getting caught by their CC either way.");
end
	


rule "Warden vs Burst, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "burst"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a burster, with heavy CC and burst potential you will need to pick your fights carefully. They don't have a lot of sustain, and once they use their abilities they become very vulnerable. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end
	





rule "Warden vs Battlemage, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "Warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time. You have a lot of sustain as well, so you should be safe in short trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but avoid fights altogether.");
end
	


rule "Warden vs Battlemage, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "battlemage"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a battlemage, with their overwhelming sustained area damage you need to prevent long trades. They have sustain, where they are ready to prevent death for a long time. You have a lot of sustain as well, so you should be safe in short trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end
	




rule "Warden vs Artillery, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be careful against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range. You have a lot of sustain as well, so you should be safe in short trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but avoid fights altogether.");
end
	


rule "Warden vs Artillery, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "artillery"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an artillery, be careful against their superior range and poke possibilities. They don't have a lot of mobility, and are fairly weak once you get in close range. You have a lot of sustain as well, so you should be safe in short trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end




rule "Warden vs Vanguard, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so quick trades should be in your favor, so saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh.");
end
	


rule "Warden vs Vanguard, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "vanguard"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a vanguard, you need to be aware of their tankiness and sustain, but don't underestimate their damage. They are not as mobile, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end




rule "Warden vs Warden, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against another warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain, so saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh.");
end
	


rule "Warden vs Warden, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "warden"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against another warden, you need to find a way to penetrate their defense. They lack the mobility and damage, but can feel overwhelmingly tough to face because of their sustain. Saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end




rule "Warden vs Catcher, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but avoid getting caught by their CC either way.");
end
	


rule "Warden vs Catcher, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "catcher"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against a catcher, be carefull of their heavy CC lockdowns. They are not as strong when their abilities are on cooldown so fight them than. You have a lot of sustain, so you should be safe in trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end



rule "Warden vs Enchanter, ally hardCC + disengage + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			disengage == true,
			sustain == true,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelessly. You have a lot of sustain, so you should be safe in short trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. Try to use your disengage when trades become to harsh, but avoid fights altogether.");
end
	


rule "Warden vs Enchanter, ally hardCC + sustain, ally def"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane: lane,
			hardCC == true,
			sustain == true,
			disengage == false,
			playType == "def"
		)
		$enemy : EnemyChampion(
			lane == $allyLane,
			role == "enchanter"
		)
	then
		//adviceStorage.addAdvice($allyLane, "early", "Against an enchanter, you should know they don't have a lot of damage output. They still have quite a bit of utility and CC, so do not engage carelessly. You have a lot of sustain, so you should be safe in short trades and saving your CC for ganks will definitely either keep you safe or lead to a kill from your jungler. ");
end

 