package com.siit.sbnz.sbnztim14.rules

import com.siit.sbnz.sbnztim14.model.Champion;
import com.siit.sbnz.sbnztim14.model.AllyChampion;
import com.siit.sbnz.sbnztim14.model.EnemyChampion;
import com.siit.sbnz.sbnztim14.model.TeamComposition;
import com.siit.sbnz.sbnztim14.model.AdviceStorage;

global com.siit.sbnz.sbnztim14.model.AdviceStorage adviceStorage;



// SPLIT PUSH


rule "Assassin, mid-late game, (split push), ally mobility + hardCC + splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == true,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a split push comp you should focus on pushing towers, whilist eliminating unaware enemies who come to stop you. You have a lot of hard cc, so they shouldn’t be hard to deal with if you can lock them down. With your mobility moving around the map is crucial.");
end

rule "Assassin, mid-late game, (split push), ally mobility + splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == false,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a split push comp you should focus on pushing towers, whilist eliminating unaware enemies who come to stop you. You are quite good at bursting weak enemies so avoid fighting bulkier opponents. With your mobility moving around the map is crucial.");
end

rule "Assassin, mid-late game, (split push), ally mobility + hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == true,
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a split push comp you should focus on eliminating enemies that try to stop your solo laners. You have a lot of hard CC so it shouldn’t be a problem to kill unaware enemis and prevent them from escaping. With your mobility moving around the map shouldn’t be a problem.");
end

rule "Assassin, mid-late game, (split push), ally mobility"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == false,
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a split push comp you should focus on eliminating enemies that try to stop your solo laners. You have a lot of burst potential to kill unaware enemis but be careful of bulkier opponents. With your mobility moving around the map shouldn’t be a problem.");
end



// Siege


rule "Assassin, mid-late game, (siege), ally hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == true,
			waveclear == false
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a siege comp your job is to prevent teamfights by killing their backline early. You have a lot of hard CC so they shouldn’t be able to escape you easily, but still be careful not to die in vain.");
end

rule "Assassin, mid-late game, (siege), ally waveclear"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == false,
			waveclear == true
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a siege comp your job is to prevent teamfights by killing their backline early. You have a lot of waveclear, so if killing the enemy is not an option use your abilities to help protect your objectives.");
end

rule "Assassin, mid-late game, (siege), ally nothing"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == false,
			waveclear == false
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a siege comp your job is to prevent teamfights by killing their backline early. You got burst potential, but be careful and chose the time to strike them.");
end


// Protect


rule "Assassin, mid-late game, (protect), ally hardCC + disengage"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == true,
			disengage == true
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a protect comp your position is to defend by attacking. You need to take out the enemy carries, so use your hard CC when you engage to prevent their escape and your disengage to get off scot free.");
end


rule "Assassin, mid-late game, (protect), ally hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == true,
			disengage == false
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a protect comp your position is to defend by attacking. You need to take out the enemy carries, so use your hard CC when you engage to prevent their escape and try to escape without taking to much damage.");
end


rule "Assassin, mid-late game, (protect), ally nothing"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == false,
			disengage == false
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a protect comp your position is to defend by attacking. You need to take out the enemy carries, so use your burst potential and try to escape without taking to much damage.");
end


// Attack


rule "Assassin, mid-late game, (attack), ally hardCC + hardEngage"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in an attack comp your focus is to destroy the enemy backline. You have a hard engage, that will be devastating to the enemy and using your hard CC you can lock them down and prevent their escape. ");
end


rule "Assassin, mid-late game, (attack), ally hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in an attack comp your focus is to destroy the enemy backline. You have your hard CC to lock down and burst enemies with ease, but be careful against tankier opponents. ");
end


rule "Assassin, mid-late game, (attack), ally nothing"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			hardCC == false,
			hardEngage == false
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in an attack comp your focus is to destroy the enemy backline. You have a lot of burst potential so try to kill enemies among the chaos of the teamfight.");
end


// Catch


rule "Assassin, mid-late game, (catch), ally mobility + hardCC + hardEngage"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == true,
			hardEngage == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a catch comp your focus is to take out enemies before fights to give yourself an edge. You have a lot of CC and combining that with your hard engages, not many enemies should be able to avoid it. If things get out of hand use your mobility to reposition and try again.");
end

rule "Assassin, mid-late game, (catch), ally mobility + hardCC"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == true,
			hardEngage == false
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a catch comp your focus is to take out enemies before fights to give yourself an edge. You have a lot of CC and burst, so not many enemies should sustain your attacks. If things get out of hand use your mobility to reposition and try again.");
end

rule "Assassin, mid-late game, (catch), ally mobility"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "assassin",
			$allyLane : lane,
			mobility == true,
			hardCC == false,
			hardEngage == false
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As an assassin in a catch comp your focus is to take out enemies before fights to give yourself an edge. You have a lot of burst so try to go for weaker enemies first. If things get out of hand use your mobility to reposition and try again.");
end

