package com.siit.sbnz.sbnztim14.rules

import com.siit.sbnz.sbnztim14.model.Champion;
import com.siit.sbnz.sbnztim14.model.AllyChampion;
import com.siit.sbnz.sbnztim14.model.EnemyChampion;
import com.siit.sbnz.sbnztim14.model.TeamComposition;
import com.siit.sbnz.sbnztim14.model.AdviceStorage;

global com.siit.sbnz.sbnztim14.model.AdviceStorage adviceStorage;



// SPLIT PUSH

rule "Warden, mid-late game, (split push), ally hardCC + sustain + splitPush"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			sustain == true,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in a split push comp your job is to push lanes whilist pressuring them to take you down. You have a lot of hard CC so engages on you can be stopped easily, and with your sustain you will be able to whistand in a lane for a long time.");
end

rule "Warden, mid-late game, (split push), ally hardCC + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			sustain == true,
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in a split push comp your job is to protect your team while solo laners push towers. You have a lot of hard CC so engages on the team can be stopped easily, and with your sustain you will be able to whistand a lot of damage to allow your team to escape.");
end


// Siege

rule "Warden, mid-late game, (siege), ally hardCC + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in a siege comp your job is to be a meatshiled for your team, while they poke and siege towers. You have a lot of hard CC to stop the enemy team engages and sustain to block incoming damage for the team.");
end


// Protect

rule "Warden, mid-late game, (protect), ally hardCC + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in a protect comp your focus is to keep enemies away from your backline carry. You are very beefy and with your hard CC they shouldn’t ignore you. You have a lot of sustain, so you won’t be easy to take down.");
end

// Attack

rule "Warden, mid-late game, (attack), ally hardCC + hardEngage + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in an attack comp your focus is to get the enemy backline to attack you and to stop their frontline from advancing. You have a great engage tool, so utilize it and combine with your hard CC to wreck havoc on them. With your sustain you will be hard to take down.");
end


rule "Warden, mid-late game, (attack), ally hardCC + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in an attack comp your focus is to get the enemy backline to attack you and to stop their frontline from advancing. You have your hard CC to prevent their engages and escapes and with your sustain you will be hard to take down, so will be a constant treat.");
end

// Catch


rule "Warden, mid-late game, (catch), ally hardCC + hardEngage + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			hardEngage == true,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in a catch comp your job is to engage and start up fights when the enemy is broken apart. Your hard engages and excellent CC can lock the enemy down, preventing their escape. You are very tanky with your sustain as well, so do not be afraid to engage when you see the opportunity.");
end


rule "Warden, mid-late game, (catch), ally hardCC + sustain"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "warden",
			$allyLane : lane,
			hardCC == true,
			hardEngage == false,
			sustain == true
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a warden in a catch comp your job is to engage and start up fights when the enemy is broken apart. Your hard CC can lock the enemy down preventing their escape and with your sustain you are very tanky so do not be afraid to engage when you see the opportunity.");
end
