package com.siit.sbnz.sbnztim14.midGame

import com.siit.sbnz.sbnztim14.model.Champion;
import com.siit.sbnz.sbnztim14.model.AllyChampion;
import com.siit.sbnz.sbnztim14.model.EnemyChampion;
import com.siit.sbnz.sbnztim14.model.TeamComposition;
import com.siit.sbnz.sbnztim14.model.MidGame;
import com.siit.sbnz.sbnztim14.model.AdviceStorage;
import com.siit.sbnz.sbnztim14.model.GameEvent;
import com.siit.sbnz.sbnztim14.model.EventType;
import java.util.List;

global com.siit.sbnz.sbnztim14.model.AdviceStorage adviceStorage;

rule "Modify values"
    no-loop
	agenda-group "mid-game"
    salience 100
    when
        $ally: AllyChampion(
            $allyLane: lane
        )
        $mid: MidGame(
            lane == $allyLane
        )
        Number($allyKills: intValue ) from accumulate(
            GameEvent($this: this, lane == $allyLane, eventType == EventType.ALLY_KILLS ),
            count($this)
        )
        Number($enemyKills: intValue ) from accumulate(
            GameEvent($this: this, lane == $allyLane, eventType == EventType.ENEMY_KILLS ),
            count($this)
        )
        Number($allyTowers: intValue ) from accumulate(
            GameEvent($this: this, lane == $allyLane, eventType == EventType.ALLY_TOWER_DESTROYED ),
            count($this)
        )
        Number($enemyTowers: intValue ) from accumulate(
            GameEvent($this: this, lane == $allyLane, eventType == EventType.ENEMY_TOWER_DESTROYED ),
            count($this)
        )
        Number($allyObjectives: intValue ) from accumulate(
            GameEvent($this: this, lane == $allyLane, eventType == EventType.OBJECT_KILLED ),
            count($this)
        )
        Number($enemyObjectives: intValue ) from accumulate(
            GameEvent($this: this, lane == $allyLane, eventType == EventType.ENEMY_OBJECT_KILLED ),
            count($this)
        )
    then
        modify($mid){ setAllyKills($allyKills)};
        modify($mid){ setAllyTowers($allyTowers)};
        modify($mid){ setEnemyKills($enemyKills)};
        modify($mid){ setEnemyTowers($enemyTowers)};
        modify($mid){ setAllyObjectives($allyObjectives)};
        modify($mid){ setEnemyObjectives($enemyObjectives)};
 end


// ATTACK
// aggro

rule "Attack, ally lane kills and towers, ally aggro"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "aggro",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyKills >= enemyKills + 5,
			allyTowers >= enemyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With a kill and tower lead you should take this opportunity to push out the enemy and rotate to take objectives with your pressure. ");
end


rule "Attack, ally lane towers, enemy lane kills, ally aggro"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "aggro",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyKills >= allyKills + 5,
			allyTowers >= enemyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "You are behind in kills, so try not to give up a bigger lead so switch to a more defensive playstyle and ask for help to fight them off.");
end



rule "Attack, ally lane kills, enemy lane towers, ally aggro"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "aggro",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyKills >= enemyKills + 5,
			enemyTowers >= allyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With a kill lead you should take this opportunity to push the enemy laner and take their lane objectives to match what they took.");
end


rule "Attack, enemy lane kills and towers, ally aggro"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "aggro",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyKills >= allyKills + 5,
			enemyTowers >= allyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "You are behind in kills and towers, so try not to give up a bigger lead so switch to a more defensive playstyle, but if they rotate follow them and play aggresively like usual");
end


rule "Attack, ally lane towers , ally aggro"
	agenda-group "mid-game"
	salience 0
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "aggro",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyTowers > enemyTowers,
			(allyKills <= enemyKills && enemyKills-allyKills <= 4) || (allyKills > enemyKills && allyKills - enemyKills <= 4)
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With their tower gone, you can safely rotate to be with your team and push things like objectives and towers with your teamfight ability.");
end

rule "Attack, enemy lane towers, ally aggro"
	agenda-group "mid-game"
	salience 0
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "aggro",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyTowers > allyTowers,
			(allyKills <= enemyKills && enemyKills-allyKills <= 4) || (allyKills > enemyKills && allyKills - enemyKills <= 4)
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "Since your towers got pushed, if they stay on the lane you should change to a more defensive play style, but if they rotate continue playing aggressively and rotate to your team as well.");
end


// def

rule "Attack, ally lane kills and towers, ally def"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "def",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyKills >= enemyKills + 5,
			allyTowers >= enemyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With a kill lead you should switch to a more aggressive platystyle and punish your lane opponent more or rotate to take other objectives.");
end


rule "Attack, ally lane towers, enemy lane kills, ally def"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "def",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyKills >= allyKills + 5,
            allyTowers >= enemyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "You are behind in kills but not in towers, so ask for help from your team while they try to break down your towers.");
end



rule "Attack, ally lane kills, enemy lane towers, ally def"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "def",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyKills >= enemyKills + 5,
            enemyTowers >= allyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With a kill lead you should switch to a more aggressive platystyle and punish your lane opponent more by taking their objective.");
end


rule "Attack, enemy lane kills and towers, ally def"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "def",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyKills >= allyKills + 5,
		    enemyTowers >= allyTowers
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "You are behind in kills and towers, and even if you were playing defensively it didn't help much, so ask for help from your team while trying to catch up.");
end


rule "Attack, ally lane towers, ally def"
	agenda-group "mid-game"
	salience 0
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "def",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyTowers > enemyTowers,
			(allyKills <= enemyKills && enemyKills-allyKills <= 4) || (allyKills > enemyKills && allyKills - enemyKills <= 4)
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With their tower gone, you can safely rotate to help the team with their lanes and force fights.");
end

rule "Attack, enemy lane towers, ally def"
	agenda-group "mid-game"
	salience 0
	when
		$ally : AllyChampion(
			lane != "jungle",
			playType == "def",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyTowers > allyTowers,
			(allyKills <= enemyKills && enemyKills-allyKills <= 4) || (allyKills > enemyKills && allyKills - enemyKills <= 4) 
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "Since your towers got pushed, if they stay on the lane you should ask for help as you can't handle them alone, but if they rotate push their lane back or rotate with them.");
end


// jungle

rule "Attack (jungle), ally objectives"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane == "jungle",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			allyObjectives >= enemyObjectives + 2
		)
	then
		
        adviceStorage.addAdvice($allyLane, "mid", "You should try keeping up the pressure with objectives, keeping your team close around objective spawn times, and making them regret attempting to take it from you.");
end

rule "Attack (jungle), enemy objectives"
	agenda-group "mid-game"
	salience 1
	when
		$ally : AllyChampion(
			lane == "jungle",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
		$midGame : MidGame(
			lane == $allyLane,
			enemyObjectives >= allyObjectives + 2
		)
	then
		adviceStorage.addAdvice($allyLane, "mid", "With your great teamfighting ability, wait for them to start objectives and then go for a teamfight using everything you can to contest it.");
end
