package com.siit.sbnz.sbnztim14.additionalRules

import com.siit.sbnz.sbnztim14.model.Champion;
import com.siit.sbnz.sbnztim14.model.AllyChampion;
import com.siit.sbnz.sbnztim14.model.EnemyChampion;
import com.siit.sbnz.sbnztim14.model.GameEvent;
import com.siit.sbnz.sbnztim14.model.Item;
import com.siit.sbnz.sbnztim14.model.ItemBuy;
import com.siit.sbnz.sbnztim14.model.EventType;
import com.siit.sbnz.sbnztim14.model.ChampionType
import java.util.ArrayList;
import java.util.List
import java.util.Arrays;

rule "increase value"
    lock-on-active
    agenda-group "items"
    salience 100
    when
        $ally: AllyChampion(
            $allyLane: lane
        )
        $i: ItemBuy(
            lane == $allyLane
        )
        Number($val: intValue() > 0)
        from accumulate(
            $e: GameEvent(
                lane == $allyLane,
                eventType == EventType.ALLY_KILLS
            ),
            count($e)
        )
    then
        modify($i){ setValue($val) };
        System.out.println("increase");
end

rule "decrease value"
    lock-on-active
    agenda-group "items"
    salience 50
    when
        $ally: AllyChampion(
            $allyLane: lane
        )
        $i: ItemBuy(
            lane == $allyLane
        )
        Number($val: intValue() > 0)
        from accumulate(
            $e: GameEvent(
                lane == $allyLane,
                eventType == EventType.ENEMY_KILLS
            ),
            count($e)
        )
    then
        modify($i){ setValue($i.getValue() - $val) };
        System.out.println("decrease");
end


rule "Buy Rabadons Deathcap2"
    agenda-group "items"
    salience (5.5 - $br)
    when
        $ally: AllyChampion(
            $lane: lane,
            wantedItem == null,
            championType == ChampionType.AP
        )
        $enemy: EnemyChampion(
            lane == $lane
        )
        $i: ItemBuy(
            lane == $lane,
            value >= 3
        )
        $item: Item(
            name == "Rabadons Deathcap2"
        )
        Number($br: intValue > -1)
            from accumulate(
                Item(
                    $temp: this,
                    name == "Rabadons Deathcap2",
                    this memberOf $ally.getBought()
                ),
                count($temp)
        )
    then
        modify($ally){ setWantedItem($item) };
        System.out.println($ally.getWantedItem().toString());
        System.out.println($br + " DVA");
end


rule "Buy Rabadons Deathcap"
    agenda-group "items"
    salience (6 - $br)
    when
        $ally: AllyChampion(
            $lane: lane,
            wantedItem == null,
            championType == ChampionType.AP
        )
        $enemy: EnemyChampion(
            lane == $lane
        )
        $i: ItemBuy(
            lane == $lane,
            value >= 3
        )
        $item: Item(
            name == "Rabadons Deathcap"
        )
        Number($br: intValue > -1)
            from accumulate(
                Item(
                    $temp: this,
                    name == "Rabadons Deathcap",
                    this memberOf $ally.getBought()
                ),
                count($temp)
        )
    then
        modify($ally){ setWantedItem($item) };
        System.out.println($ally.getWantedItem().toString());
        System.out.println($br);
end

