package com.siit.sbnz.sbnztim14.teamcomp

import com.siit.sbnz.sbnztim14.model.Champion;
import com.siit.sbnz.sbnztim14.model.AllyChampion;
import com.siit.sbnz.sbnztim14.model.EnemyChampion;
import com.siit.sbnz.sbnztim14.model.TeamComposition;
import com.siit.sbnz.sbnztim14.model.AdviceStorage;

global com.siit.sbnz.sbnztim14.model.AdviceStorage adviceStorage;



// SPLIT PUSH

rule "Marksman, mid-late game, (split push)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane : lane,
			hardCC == true,
			waveclear == true,
			disengage == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a marksman in a split push comp your job is to put pressure on the enemy while your solo laners get the job done. You have hard CC so locking down enemies who try to attack you shouldn’t be an issue, using your waveclear to prevent sieges and disengage when fights get to close.");
end

// Siege

rule "Marksman, mid-late game, (siege)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a marksman in a siege comp your main job is to prevent pushes and tear down opponents from far away. Using your poke you can do that with ease, using your waveclear to prevent pushes and siege towers.");
end




// Protect

rule "Marksman, mid-late game, (protect)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a marksman in a protect comp you are the main source of damage. You have to stay alive as long as possible, and your hard cc should see to that. You do have waveclear as to protect yourself from pushes and keep your base alive.");
end


// Attack

rule "Marksman, mid-late game, (attack)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a marksman in an attack comp your position is be safe and supply damage to the team as long as possible. You have a hard engage that can give your team an opportunity to attack, and with your hard CC you can either keep yourself and others safe or secure kills.");
end


// Catch

rule "Marksman, mid-late game, (catch)"
	when
		$ally : AllyChampion(
			lane != "jungle",
			role == "marksman",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a marksman in a catch comp your position is to prevent fights from happening whilist your teammates pick enemies one by one. With your waveclear you can sustain your base against multiple opponents and even counter push. Use your disengage when enemies get to close.");
end
