package com.siit.sbnz.sbnztim14.teamcomp

import com.siit.sbnz.sbnztim14.model.Champion;
import com.siit.sbnz.sbnztim14.model.AllyChampion;
import com.siit.sbnz.sbnztim14.model.EnemyChampion;
import com.siit.sbnz.sbnztim14.model.TeamComposition;
import com.siit.sbnz.sbnztim14.model.AdviceStorage;

global com.siit.sbnz.sbnztim14.model.AdviceStorage adviceStorage;



// SPLIT PUSH

rule "Skirmisher, mid-late game, (split push), splitPush"
	agenda-group "teamcomp-role"
	when
		$ally : AllyChampion(
			role == "skirmisher",
			$allyLane : lane,
			splitPush == true
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a skirmisher in a split push comp your focus is to push towers and outsustain multiple enemies attacking you. You have a lot of hard CC so if someone gets close they shouldn't be hard to deal with. As mentioned you do have sustain, so fighting and staying a bit longer in lane will not be an issue. ");
end


rule "Skirmisher, mid-late game, (split push), ally sustain + hardCC"
	agenda-group "teamcomp-role"
	when
		$ally : AllyChampion(
			role == "skirmisher",
			$allyLane : lane,			
			splitPush == false
		)
		$composition : TeamComposition(
			composition == "splitPush"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a skirmisher in a split push comp your focus is to prolong fights so your team can push lanes. You have a lot of hard CC so if someone gets close they wouldn't be to hard to deal with and using your sustain you can fight multiple opponents with ease.");
end



// Siege

rule "Skirmisher, mid-late game, (siege)"
	agenda-group "teamcomp-role"
	when
		$ally : AllyChampion(
			role == "skirmisher",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "siege"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a skirmisher in a siege comp you should focus on preventing the enemy from reaching your backline. You have a lot of hard CC to stop them, and a lot of sustain to stay viable in fights for a long time.");
end


// Protect

rule "Skirmisher, mid-late game, (protect)"
	agenda-group "teamcomp-role"
	when
		$ally : AllyChampion(
			role == "skirmisher",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "protect"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a juggernaut in a protect comp your position is to defend your teammates in fights and protect objectives. You have a lot of sustain, so you can take a beating and with your hard CC fights can be turned to your favor.");
end


// Attack

rule "Skirmisher, mid-late game, (attack)"
	agenda-group "teamcomp-role"
	when
		$ally : AllyChampion(
			role == "skirmisher",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "attack"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a skirmisher in an attack comp your position is to deal with the frontline while the others take down the carries. With your hard CC lock the tanks down, preventing them from moving from you. Do not worry since with your sustain you should be able to duel them easily.");
end

// Catch

rule "Skirmisher, mid-late game, (catch)"
	agenda-group "teamcomp-role"
	when
		$ally : AllyChampion(
			role == "skirmisher",
			$allyLane : lane
		)
		$composition : TeamComposition(
			composition == "catch"
		)
	then
		adviceStorage.addAdvice($allyLane, "mid-late", "As a skirmisher in a siege comp you should focus on preventing the enemy from reaching your backline. You have a lot of hard CC to stop them, and a lot of sustain to stay viable in fights for a long time.");
end
